name: Daily Commit Workflow

on:
  schedule:
    - cron: "30 4 * * *"  # Daily at 04:30 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make daily commit 24f2005847@ds.study.iitm.ac.in
        run: |
          echo "$(date)" > daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit at $(date)"
          git push
